plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.jlink' version '4.1.0'
    id 'org.gradlex.extra-java-module-info' version '1.13.1'
}

group = 'training'
version = '1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

extraJavaModuleInfo {
    automaticModule('com.beust:jcommander', 'com.beust.jcommander')
    automaticModule('org.slf4j:slf4j-api', 'org.slf4j')
    automaticModule('com.nativelibs4java:bridj', 'bridj')
    automaticModule('commons-logging:commons-logging', 'commons.logging')
    automaticModule('commons-collections:commons-collections', 'commons.collections')
    automaticModule('commons-beanutils:commons-beanutils', 'commons.beanutils')
    automaticModule('com.github.jai-imageio:jai-imageio-core', 'jai.imageio.core')
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.swing']
}

application {
    mainClass = 'training.Main'
}

jlink {
    imageZip = project.file("${buildDir}/distributions/TrainingApp-image.zip")
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']

    mergedModule {
        requires 'java.desktop'
    }

    launcher {
        name = 'TrainingApp'
        jvmArgs = ['-Dfile.encoding=UTF-8']
    }

    jpackage {
        imageName = 'TrainingApp'
        appVersion = '1.0'
        imageOptions = ['--win-console']
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.google.zxing:javase:3.5.3'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.controlsfx:controlsfx:11.2.4'
}
test {
    useJUnitPlatform()
}